# Generated by Django 4.2 on 2025-04-17 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('manager', models.CharField(max_length=50)),
                ('date_establishment', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.BooleanField(choices=[(1, 'Nam'), (0, 'Nữ')])),
                ('birthday', models.DateTimeField()),
                ('place_of_birth', models.CharField(max_length=300)),
                ('place_of_origin', models.CharField(max_length=300)),
                ('place_of_residence', models.CharField(max_length=300)),
                ('identification', models.CharField(max_length=50, unique=True)),
                ('date_of_issue', models.DateTimeField()),
                ('place_of_issue', models.CharField(max_length=300)),
                ('nationality', models.CharField(max_length=50)),
                ('nation', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=300)),
                ('avatar', models.TextField(blank=True)),
                ('marital_status', models.IntegerField(choices=[(0, 'Độc thân'), (1, 'Đã kết hôn'), (2, 'Ly hôn')])),
                ('job_position', models.CharField(max_length=50)),
                ('salary', models.FloatField()),
                ('contract_start_date', models.DateTimeField()),
                ('contract_duration', models.FloatField(help_text='Đơn vị tháng')),
                ('status', models.IntegerField(choices=[(0, 'Onboarding'), (1, 'Thử việc'), (2, 'Nhân viên chính thức'), (3, 'Đã nghỉ việc'), (4, 'Bị sa thải')])),
                ('education_level', models.CharField(max_length=50)),
                ('scholl', models.CharField(max_length=100)),
                ('certificate', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.department')),
            ],
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('salary_coefficient', models.FloatField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('cash_payment', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('salary', models.FloatField()),
                ('bonus', models.FloatField()),
                ('deductions', models.FloatField()),
                ('net_salary', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=50)),
                ('score', models.FloatField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.jobtitle'),
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Có làm việc', 'Có làm việc'), ('Nghỉ phép', 'Nghỉ phép'), ('Nghỉ không phép', 'Nghỉ không phép')], max_length=50)),
                ('working_hours', models.FloatField(default=0)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
        ),
    ]
