# Generated by Django 4.1.1 on 2025-04-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='scholl',
            new_name='school',
        ),
        migrations.AlterField(
            model_name='employee',
            name='education_level',
            field=models.IntegerField(choices=[(0, 'Phổ thông'), (1, 'Trung cấp'), (2, 'Cao Đẳng'), (3, 'Đại học'), (4, 'Thạc sĩ'), (5, 'Tiến sĩ'), (6, 'Khác')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Nam'), (1, 'Nữ'), (2, 'Khác')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='marital_status',
            field=models.IntegerField(choices=[(0, 'Độc thân'), (1, 'Đã kết hôn'), (2, 'Đã ly hôn')]),
        ),
    ]
