# Generated by Django 4.2.16 on 2025-11-22 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('general', 'Thông báo chung'), ('event', 'Sự kiện'), ('policy', 'Chính sách'), ('holiday', 'Ngày nghỉ'), ('training', 'Đào tạo'), ('reward', 'Khen thưởng'), ('other', 'Khác')], default='general', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Thấp'), ('normal', 'Bình thường'), ('high', 'Cao'), ('urgent', 'Khẩn cấp')], default='normal', max_length=20)),
                ('target_all', models.BooleanField(default=True, help_text='Gửi cho tất cả nhân viên')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='announcements/%Y/%m/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_pinned', models.BooleanField(default=False, help_text='Ghim lên đầu')),
                ('publish_at', models.DateTimeField(help_text='Thời gian xuất bản')),
                ('expire_at', models.DateTimeField(blank=True, help_text='Hết hạn (optional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to='app.employee')),
                ('target_departments', models.ManyToManyField(blank=True, to='app.department')),
                ('target_employees', models.ManyToManyField(blank=True, related_name='targeted_announcements', to='app.employee')),
            ],
            options={
                'ordering': ['-is_pinned', '-publish_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('file_size', models.IntegerField(default=0, help_text='Size in bytes')),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('visibility', models.CharField(choices=[('all', 'Tất cả nhân viên'), ('department', 'Chỉ phòng ban'), ('manager', 'Chỉ quản lý'), ('specific', 'Nhân viên cụ thể')], default='all', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('downloads_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='fa-folder', help_text='Font Awesome icon class', max_length=50)),
                ('color', models.CharField(default='primary', help_text='Bootstrap color: primary, success, info, etc.', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Document Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_logs', to='app.document')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
            options={
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='app.documentcategory'),
        ),
        migrations.AddField(
            model_name='document',
            name='departments',
            field=models.ManyToManyField(blank=True, help_text='Nếu visibility=department', to='app.department'),
        ),
        migrations.AddField(
            model_name='document',
            name='specific_employees',
            field=models.ManyToManyField(blank=True, help_text='Nếu visibility=specific', related_name='accessible_documents', to='app.employee'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to='app.employee'),
        ),
        migrations.CreateModel(
            name='AnnouncementRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_logs', to='app.announcement')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
            options={
                'ordering': ['-read_at'],
                'unique_together': {('announcement', 'employee')},
            },
        ),
    ]
