# Generated by Django 4.2.16 on 2025-11-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_announcement_document_documentcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='company_feedback',
            field=models.TextField(blank=True, help_text='Góp ý của nhân viên cho công ty'),
        ),
    ]
