# Generated by Django 4.1.1 on 2025-04-24 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_scholl_employee_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birthday',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contract_start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_issue',
            field=models.DateField(),
        ),
    ]
