# Generated by Django 4.2.16 on 2025-12-02 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_add_company_feedback_to_appraisal'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Công ty TNHH ABC', max_length=200, verbose_name='Tên công ty')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='Logo công ty')),
                ('company_address', models.TextField(blank=True, default='', verbose_name='Địa chỉ')),
                ('company_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Số điện thoại')),
                ('company_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email công ty')),
                ('company_website', models.URLField(blank=True, default='', verbose_name='Website')),
                ('company_tax_code', models.CharField(blank=True, default='', max_length=20, verbose_name='Mã số thuế')),
                ('standard_working_days', models.IntegerField(default=22, verbose_name='Ngày làm việc tiêu chuẩn/tháng')),
                ('standard_working_hours', models.DecimalField(decimal_places=2, default=8, max_digits=4, verbose_name='Giờ làm việc/ngày')),
                ('work_start_time', models.TimeField(default='08:00', verbose_name='Giờ bắt đầu làm việc')),
                ('work_end_time', models.TimeField(default='17:00', verbose_name='Giờ kết thúc làm việc')),
                ('lunch_break_start', models.TimeField(default='12:00', verbose_name='Giờ nghỉ trưa bắt đầu')),
                ('lunch_break_end', models.TimeField(default='13:00', verbose_name='Giờ nghỉ trưa kết thúc')),
                ('timezone', models.CharField(default='Asia/Ho_Chi_Minh', max_length=50, verbose_name='Múi giờ')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=10, help_text='Thuế thu nhập cá nhân cơ bản', max_digits=5, verbose_name='Thuế TNCN cơ bản (%)')),
                ('tax_deduction_personal', models.DecimalField(decimal_places=0, default=11000000, help_text='Mức giảm trừ gia cảnh bản thân', max_digits=15, verbose_name='Giảm trừ bản thân')),
                ('tax_deduction_dependent', models.DecimalField(decimal_places=0, default=4400000, help_text='Mức giảm trừ cho mỗi người phụ thuộc', max_digits=15, verbose_name='Giảm trừ người phụ thuộc')),
                ('social_insurance_rate', models.DecimalField(decimal_places=2, default=8, max_digits=5, verbose_name='BHXH người lao động (%)')),
                ('health_insurance_rate', models.DecimalField(decimal_places=2, default=1.5, max_digits=5, verbose_name='BHYT người lao động (%)')),
                ('unemployment_insurance_rate', models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='BHTN người lao động (%)')),
                ('employer_social_insurance_rate', models.DecimalField(decimal_places=2, default=17.5, max_digits=5, verbose_name='BHXH người sử dụng LĐ (%)')),
                ('employer_health_insurance_rate', models.DecimalField(decimal_places=2, default=3, max_digits=5, verbose_name='BHYT người sử dụng LĐ (%)')),
                ('employer_unemployment_insurance_rate', models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='BHTN người sử dụng LĐ (%)')),
                ('minimum_wage', models.DecimalField(decimal_places=0, default=4960000, help_text='Lương tối thiểu vùng I', max_digits=15, verbose_name='Lương tối thiểu vùng')),
                ('social_insurance_max_salary', models.DecimalField(decimal_places=0, default=46800000, help_text='20 lần lương tối thiểu', max_digits=15, verbose_name='Mức đóng BHXH tối đa')),
                ('email_host', models.CharField(blank=True, default='smtp.gmail.com', max_length=200, verbose_name='SMTP Server')),
                ('email_port', models.IntegerField(default=587, verbose_name='SMTP Port')),
                ('email_use_tls', models.BooleanField(default=True, verbose_name='Sử dụng TLS')),
                ('email_use_ssl', models.BooleanField(default=False, verbose_name='Sử dụng SSL')),
                ('email_host_user', models.CharField(blank=True, default='', max_length=200, verbose_name='Email username')),
                ('email_host_password', models.CharField(blank=True, default='', help_text='App password cho Gmail', max_length=200, verbose_name='Email password')),
                ('email_from_name', models.CharField(blank=True, default='HRM System', max_length=100, verbose_name='Tên người gửi')),
                ('notify_leave_approved', models.BooleanField(default=True, verbose_name='Thông báo duyệt nghỉ phép')),
                ('notify_expense_approved', models.BooleanField(default=True, verbose_name='Thông báo duyệt chi phí')),
                ('notify_contract_expiring', models.BooleanField(default=True, verbose_name='Cảnh báo hợp đồng sắp hết hạn')),
                ('contract_expiring_days', models.IntegerField(default=30, help_text='Cảnh báo trước bao nhiêu ngày', verbose_name='Số ngày cảnh báo HĐ')),
                ('notify_appraisal_reminder', models.BooleanField(default=True, verbose_name='Nhắc nhở đánh giá')),
                ('notify_welcome_email', models.BooleanField(default=True, verbose_name='Gửi email chào mừng NV mới')),
                ('date_format', models.CharField(default='d/m/Y', help_text='d/m/Y hoặc Y-m-d', max_length=20, verbose_name='Định dạng ngày')),
                ('currency_symbol', models.CharField(default='VNĐ', max_length=10, verbose_name='Ký hiệu tiền tệ')),
                ('pagination_size', models.IntegerField(default=20, verbose_name='Số dòng mỗi trang')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cài đặt hệ thống',
                'verbose_name_plural': 'Cài đặt hệ thống',
            },
        ),
    ]
