# Generated by Django 4.1.1 on 2025-04-24 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_employee_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_code',
            field=models.CharField(default='TEMP', max_length=20, unique=True),
        ),
    ]
