# Generated by Django 4.1.1 on 2025-04-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_department_manager_employee_is_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='date_establishment',
            field=models.DateField(),
        ),
    ]
