# Generated by Django 4.1.1 on 2025-04-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_employee_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='field',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
