# Generated by Django 4.1.1 on 2025-04-24 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_employee_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='field',
            new_name='major',
        ),
    ]
