# Generated by Django 4.1.1 on 2025-04-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_field_employee_major'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payroll',
            old_name='deductions',
            new_name='base_salary',
        ),
        migrations.RenameField(
            model_name='payroll',
            old_name='net_salary',
            new_name='hourly_rate',
        ),
        migrations.RenameField(
            model_name='payroll',
            old_name='salary',
            new_name='salary_coefficient',
        ),
        migrations.AddField(
            model_name='payroll',
            name='month',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payroll',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='penalty',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='standard_working_days',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payroll',
            name='status',
            field=models.CharField(choices=[('pending', 'Chưa xác nhận'), ('confirmed', 'Đã xác nhận')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='payroll',
            name='total_salary',
            field=models.FloatField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payroll',
            name='total_working_hours',
            field=models.FloatField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payroll',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='year',
            field=models.IntegerField(default=2025),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payroll',
            name='bonus',
            field=models.FloatField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together={('employee', 'month', 'year')},
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='date',
        ),
    ]
