# Generated by Django 4.2.16 on 2025-11-14 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_deductions_payroll_base_salary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('max_days_per_year', models.IntegerField(help_text='Số ngày tối đa trong năm')),
                ('requires_approval', models.BooleanField(default=True, help_text='Có cần duyệt không?')),
                ('is_paid', models.BooleanField(default=True, help_text='Có hưởng lương không?')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_days', models.FloatField(help_text='Số ngày nghỉ (có thể là 0.5 cho nửa ngày)')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối'), ('cancelled', 'Đã hủy')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Người duyệt (Manager hoặc HR)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to='app.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='app.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.leavetype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('total_days', models.FloatField(help_text='Tổng số ngày phép được cấp')),
                ('used_days', models.FloatField(default=0, help_text='Số ngày đã sử dụng')),
                ('remaining_days', models.FloatField(help_text='Số ngày còn lại')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='app.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.leavetype')),
            ],
            options={
                'ordering': ['-year', 'leave_type'],
                'unique_together': {('employee', 'leave_type', 'year')},
            },
        ),
    ]
