# Generated by Django 4.2.16 on 2025-11-14 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_leavetype_leaverequest_leavebalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Expense Category',
                'verbose_name_plural': 'Expense Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Số tiền yêu cầu hoàn', max_digits=12)),
                ('date', models.DateField(help_text='Ngày phát sinh chi phí')),
                ('description', models.TextField(help_text='Mô tả chi tiết chi phí')),
                ('receipt', models.ImageField(blank=True, help_text='Ảnh hóa đơn', null=True, upload_to='receipts/')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối'), ('paid', 'Đã thanh toán'), ('cancelled', 'Đã hủy')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Tiền mặt'), ('bank_transfer', 'Chuyển khoản'), ('check', 'Séc')], max_length=50)),
                ('payment_reference', models.CharField(blank=True, help_text='Mã giao dịch/Số séc', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Người duyệt (Manager hoặc HR)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to='app.employee')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.expensecategory')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='app.employee')),
                ('paid_by', models.ForeignKey(blank=True, help_text='Người thanh toán (Kế toán)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_expenses', to='app.employee')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-created_at'],
            },
        ),
    ]
