# Generated by Django 4.2.16 on 2025-11-15 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_expensecategory_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(help_text='Số hợp đồng', max_length=50, unique=True)),
                ('contract_type', models.CharField(choices=[('probation', 'Hợp đồng thử việc'), ('definite', 'Hợp đồng xác định thời hạn'), ('indefinite', 'Hợp đồng không xác định thời hạn'), ('seasonal', 'Hợp đồng theo mùa vụ'), ('project', 'Hợp đồng theo dự án')], max_length=20)),
                ('start_date', models.DateField(help_text='Ngày bắt đầu')),
                ('end_date', models.DateField(blank=True, help_text='Ngày kết thúc (null nếu vô thời hạn)', null=True)),
                ('signed_date', models.DateField(help_text='Ngày ký')),
                ('salary', models.FloatField(help_text='Mức lương theo hợp đồng')),
                ('salary_coefficient', models.FloatField(default=1.0, help_text='Hệ số lương')),
                ('allowances', models.FloatField(default=0, help_text='Phụ cấp')),
                ('job_description', models.TextField(blank=True, help_text='Mô tả công việc')),
                ('workplace', models.CharField(help_text='Địa điểm làm việc', max_length=300)),
                ('working_hours', models.CharField(default='8 giờ/ngày, 5 ngày/tuần', help_text='Thời gian làm việc', max_length=100)),
                ('terms', models.TextField(help_text='Các điều khoản hợp đồng')),
                ('benefits', models.TextField(blank=True, help_text='Các quyền lợi')),
                ('insurance_info', models.TextField(blank=True, help_text='Thông tin bảo hiểm')),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('active', 'Đang hiệu lực'), ('expired', 'Hết hạn'), ('terminated', 'Đã chấm dứt'), ('renewed', 'Đã gia hạn')], default='draft', max_length=20)),
                ('termination_reason', models.TextField(blank=True, help_text='Lý do chấm dứt')),
                ('termination_date', models.DateField(blank=True, help_text='Ngày chấm dứt', null=True)),
                ('notes', models.TextField(blank=True, help_text='Ghi chú')),
                ('contract_file', models.FileField(blank=True, help_text='File hợp đồng scan', upload_to='contracts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Người tạo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to='app.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='app.employee')),
                ('job_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.jobtitle')),
                ('renewed_from', models.ForeignKey(blank=True, help_text='Hợp đồng được gia hạn từ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='app.contract')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'ordering': ['-created_at'],
            },
        ),
    ]
