# Generated by Django 4.2.16 on 2025-11-15 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_code', models.CharField(help_text='Mã đơn ứng tuyển', max_length=50, unique=True)),
                ('full_name', models.CharField(help_text='Họ và tên', max_length=100)),
                ('email', models.EmailField(help_text='Email', max_length=254)),
                ('phone', models.CharField(help_text='Số điện thoại', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, help_text='Ngày sinh', null=True)),
                ('gender', models.IntegerField(blank=True, choices=[(0, 'Nam'), (1, 'Nữ'), (2, 'Khác')], null=True)),
                ('address', models.CharField(blank=True, help_text='Địa chỉ', max_length=300)),
                ('current_position', models.CharField(blank=True, help_text='Vị trí hiện tại', max_length=100)),
                ('current_company', models.CharField(blank=True, help_text='Công ty hiện tại', max_length=200)),
                ('years_of_experience', models.IntegerField(default=0, help_text='Số năm kinh nghiệm')),
                ('education_level', models.IntegerField(blank=True, choices=[(0, 'Phổ thông'), (1, 'Trung cấp'), (2, 'Cao Đẳng'), (3, 'Đại học'), (4, 'Thạc sĩ'), (5, 'Tiến sĩ'), (6, 'Khác')], null=True)),
                ('school', models.CharField(blank=True, help_text='Trường học', max_length=200)),
                ('major', models.CharField(blank=True, help_text='Chuyên ngành', max_length=100)),
                ('resume', models.FileField(help_text='CV ứng viên', upload_to='resumes/')),
                ('cover_letter', models.TextField(blank=True, help_text='Thư xin việc')),
                ('portfolio_url', models.URLField(blank=True, help_text='Link portfolio')),
                ('linkedin_url', models.URLField(blank=True, help_text='Link LinkedIn')),
                ('expected_salary', models.FloatField(blank=True, help_text='Mức lương mong muốn', null=True)),
                ('available_start_date', models.DateField(blank=True, help_text='Ngày có thể bắt đầu', null=True)),
                ('notice_period_days', models.IntegerField(default=0, help_text='Thời gian báo trước (ngày)')),
                ('status', models.CharField(choices=[('new', 'Mới'), ('screening', 'Sơ tuyển'), ('phone_interview', 'Phỏng vấn điện thoại'), ('interview', 'Phỏng vấn'), ('test', 'Làm bài test'), ('offer', 'Đề nghị'), ('accepted', 'Chấp nhận'), ('rejected', 'Từ chối'), ('withdrawn', 'Rút lui')], default='new', max_length=20)),
                ('source', models.CharField(choices=[('website', 'Website công ty'), ('referral', 'Giới thiệu'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('indeed', 'Indeed'), ('vietnamworks', 'VietnamWorks'), ('other', 'Khác')], default='website', max_length=20)),
                ('rating', models.IntegerField(blank=True, help_text='Đánh giá (1-5)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Ghi chú nội bộ')),
                ('interview_date', models.DateTimeField(blank=True, help_text='Ngày giờ phỏng vấn', null=True)),
                ('interview_location', models.CharField(blank=True, help_text='Địa điểm phỏng vấn', max_length=300)),
                ('offer_made_date', models.DateField(blank=True, help_text='Ngày đề nghị', null=True)),
                ('offer_accepted_date', models.DateField(blank=True, help_text='Ngày chấp nhận', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Lý do từ chối')),
                ('converted_to_employee', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Người phụ trách', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to='app.employee')),
                ('employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='app.employee')),
                ('interviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews_conducted', to='app.employee')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Tiêu đề công việc', max_length=200)),
                ('code', models.CharField(help_text='Mã tin tuyển dụng', max_length=50, unique=True)),
                ('description', models.TextField(help_text='Mô tả công việc')),
                ('requirements', models.TextField(help_text='Yêu cầu công việc')),
                ('responsibilities', models.TextField(help_text='Trách nhiệm công việc')),
                ('benefits', models.TextField(help_text='Quyền lợi')),
                ('employment_type', models.CharField(choices=[('fulltime', 'Toàn thời gian'), ('parttime', 'Bán thời gian'), ('contract', 'Hợp đồng'), ('internship', 'Thực tập')], default='fulltime', max_length=20)),
                ('experience_level', models.CharField(choices=[('entry', 'Mới tốt nghiệp'), ('junior', 'Junior (1-2 năm)'), ('mid', 'Middle (3-5 năm)'), ('senior', 'Senior (5+ năm)'), ('expert', 'Expert (10+ năm)')], default='junior', max_length=20)),
                ('number_of_positions', models.IntegerField(default=1, help_text='Số lượng cần tuyển')),
                ('location', models.CharField(help_text='Địa điểm làm việc', max_length=300)),
                ('salary_min', models.FloatField(blank=True, help_text='Lương tối thiểu', null=True)),
                ('salary_max', models.FloatField(blank=True, help_text='Lương tối đa', null=True)),
                ('salary_negotiable', models.BooleanField(default=False, help_text='Lương thỏa thuận')),
                ('deadline', models.DateField(help_text='Hạn nộp hồ sơ')),
                ('start_date', models.DateField(blank=True, help_text='Ngày dự kiến nhận việc', null=True)),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('open', 'Đang mở'), ('closed', 'Đã đóng'), ('cancelled', 'Đã hủy')], default='draft', max_length=20)),
                ('contact_person', models.CharField(blank=True, help_text='Người liên hệ', max_length=100)),
                ('contact_email', models.EmailField(blank=True, help_text='Email liên hệ', max_length=254)),
                ('contact_phone', models.CharField(blank=True, help_text='Điện thoại liên hệ', max_length=20)),
                ('views_count', models.IntegerField(default=0, help_text='Số lượt xem')),
                ('applications_count', models.IntegerField(default=0, help_text='Số lượt ứng tuyển')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_jobs', to='app.employee')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.department')),
                ('job_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.jobtitle')),
            ],
            options={
                'verbose_name': 'Job Posting',
                'verbose_name_plural': 'Job Postings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(help_text='Ghi chú')),
                ('is_important', models.BooleanField(default=False, help_text='Đánh dấu quan trọng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_notes', to='app.application')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='app.jobposting'),
        ),
    ]
