# Generated by Django 4.2.16 on 2025-11-15 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_application_jobposting_applicationnote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Mã thành phần (VD: PC_VITRI, TH_HIEUSUAT)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Tên thành phần', max_length=100)),
                ('component_type', models.CharField(choices=[('allowance', 'Phụ cấp'), ('bonus', 'Thưởng'), ('deduction', 'Khấu trừ'), ('overtime', 'Làm thêm giờ')], max_length=20)),
                ('calculation_method', models.CharField(choices=[('fixed', 'Cố định'), ('percentage', 'Phần trăm lương cơ bản'), ('formula', 'Công thức tùy chỉnh'), ('hourly', 'Theo giờ'), ('daily', 'Theo ngày')], max_length=20)),
                ('default_amount', models.FloatField(default=0, help_text='Số tiền mặc định')),
                ('percentage', models.FloatField(default=0, help_text='Phần trăm (0-100)')),
                ('formula', models.TextField(blank=True, help_text='Công thức Python (VD: base_salary * 0.1 + bonus)')),
                ('is_taxable', models.BooleanField(default=True, help_text='Tính thuế TNCN')),
                ('is_mandatory', models.BooleanField(default=False, help_text='Bắt buộc áp dụng cho tất cả')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['component_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PayrollCalculationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.FloatField()),
                ('total_allowances', models.FloatField(default=0)),
                ('total_bonuses', models.FloatField(default=0)),
                ('total_deductions', models.FloatField(default=0)),
                ('total_overtime', models.FloatField(default=0)),
                ('taxable_income', models.FloatField(default=0)),
                ('personal_income_tax', models.FloatField(default=0)),
                ('social_insurance', models.FloatField(default=0)),
                ('health_insurance', models.FloatField(default=0)),
                ('unemployment_insurance', models.FloatField(default=0)),
                ('gross_salary', models.FloatField(help_text='Tổng lương trước thuế và bảo hiểm')),
                ('net_salary', models.FloatField(help_text='Lương thực nhận')),
                ('calculation_details', models.JSONField(default=dict, help_text='Chi tiết từng component')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('calculated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.employee')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculation_logs', to='app.payroll')),
            ],
            options={
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalaryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_amount', models.FloatField(blank=True, help_text='Số tiền tùy chỉnh (override default)', null=True)),
                ('custom_percentage', models.FloatField(blank=True, help_text='Phần trăm tùy chỉnh', null=True)),
                ('custom_formula', models.TextField(blank=True, help_text='Công thức tùy chỉnh')),
                ('effective_from', models.DateField(help_text='Có hiệu lực từ ngày')),
                ('effective_to', models.DateField(blank=True, help_text='Hết hiệu lực (null = vô thời hạn)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.salarycomponent')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_salary_rules', to='app.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_rules', to='app.employee')),
            ],
            options={
                'ordering': ['-effective_from'],
                'unique_together': {('employee', 'component', 'effective_from')},
            },
        ),
    ]
