# Generated by Django 4.2.16 on 2025-11-15 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_salarycomponent_payrollcalculationlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryRuleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên template (VD: Template Giám đốc)', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.department')),
                ('job_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.jobtitle')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SalaryRuleTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_amount', models.FloatField(blank=True, null=True)),
                ('custom_percentage', models.FloatField(blank=True, null=True)),
                ('custom_formula', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.salarycomponent')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_items', to='app.salaryruletemplate')),
            ],
            options={
                'ordering': ['order', 'component__name'],
                'unique_together': {('template', 'component')},
            },
        ),
    ]
