# Generated by Django 4.2.16 on 2025-11-15 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_salaryruletemplate_salaryruletemplateitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Tạo mới'), ('renewed', 'Gia hạn'), ('salary_adjusted', 'Điều chỉnh lương'), ('terminated', 'Chấm dứt'), ('status_changed', 'Thay đổi trạng thái')], max_length=20)),
                ('description', models.TextField(help_text='Mô tả chi tiết thay đổi')),
                ('old_value', models.JSONField(blank=True, help_text='Giá trị cũ (nếu có)', null=True)),
                ('new_value', models.JSONField(blank=True, help_text='Giá trị mới', null=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Contract histories',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-start_date']},
        ),
        migrations.RemoveField(
            model_name='contract',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='contract_file',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='contract_number',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='insurance_info',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='job_description',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='salary_coefficient',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='termination_date',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='termination_reason',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='workplace',
        ),
        migrations.AddField(
            model_name='contract',
            name='attachment',
            field=models.FileField(blank=True, help_text='File hợp đồng PDF', upload_to='contracts/'),
        ),
        migrations.AddField(
            model_name='contract',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Lương cơ bản', max_digits=15),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_code',
            field=models.CharField(default='TEMP', help_text='Mã hợp đồng', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.department'),
        ),
        migrations.AddField(
            model_name='contract',
            name='work_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='contract',
            name='allowances',
            field=models.JSONField(blank=True, default=dict, help_text='Phụ cấp dạng JSON'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('probation', 'Thử việc'), ('fixed_term', 'Xác định thời hạn'), ('indefinite', 'Không xác định thời hạn'), ('seasonal', 'Thời vụ'), ('part_time', 'Bán thời gian')], max_length=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_created', to='app.employee'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(blank=True, help_text='Ngày kết thúc (null nếu không xác định thời hạn)', null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='renewed_from',
            field=models.ForeignKey(blank=True, help_text='Hợp đồng cũ được gia hạn', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='app.contract'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='signed_date',
            field=models.DateField(blank=True, help_text='Ngày ký', null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(help_text='Ngày bắt đầu hiệu lực'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('draft', 'Nháp'), ('active', 'Đang hiệu lực'), ('expired', 'Hết hạn'), ('terminated', 'Chấm dứt'), ('renewed', 'Đã gia hạn')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='terms',
            field=models.TextField(blank=True, help_text='Điều khoản hợp đồng'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='working_hours',
            field=models.CharField(default='8:00-17:00', help_text='Giờ làm việc', max_length=100),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['employee', 'status'], name='app_contrac_employe_96c0b0_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['end_date'], name='app_contrac_end_dat_7559b0_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status'], name='app_contrac_status_b794cb_idx'),
        ),
        migrations.AddField(
            model_name='contracthistory',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='app.contract'),
        ),
        migrations.AddField(
            model_name='contracthistory',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.employee'),
        ),
    ]
