# Generated by Django 4.2.16 on 2025-11-15 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_contracthistory_alter_contract_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('view_team_employees', 'Can view team employees'), ('view_employee_salary', 'Can view employee salary information'), ('view_all_employees', 'Can view all employees across departments'), ('manage_employee_contracts', 'Can manage employee contracts')]},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-created_at'], 'permissions': [('approve_expense', 'Can approve expense claims'), ('pay_expense', 'Can pay approved expenses')], 'verbose_name': 'Expense', 'verbose_name_plural': 'Expenses'},
        ),
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'ordering': ['-created_at'], 'permissions': [('approve_leave_request', 'Can approve leave requests'), ('view_team_leave_requests', 'Can view team leave requests')]},
        ),
    ]
