# Generated by Django 4.2.16 on 2025-11-15 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0019_alter_employee_options_alter_expense_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Username at time of action', max_length=150)),
                ('user_groups', models.JSONField(default=list, help_text="User's groups at time of action")),
                ('action', models.CharField(choices=[('denied', 'Access Denied'), ('granted', 'Access Granted'), ('attempted', 'Access Attempted')], default='denied', max_length=20)),
                ('resource_type', models.CharField(help_text='Contract, LeaveRequest, Expense, Payroll, etc.', max_length=50)),
                ('resource_id', models.IntegerField(blank=True, help_text='ID of the resource accessed', null=True)),
                ('permission_required', models.CharField(help_text='Permission that was checked', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('reason', models.TextField(help_text='Reason for denial or additional context')),
                ('view_name', models.CharField(blank=True, help_text='Django view name', max_length=100)),
                ('url_path', models.CharField(blank=True, max_length=500)),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Additional context (department, etc.)')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permission Audit Log',
                'verbose_name_plural': 'Permission Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='app_permiss_timesta_739c46_idx'), models.Index(fields=['user', '-timestamp'], name='app_permiss_user_id_6bc35d_idx'), models.Index(fields=['action', '-timestamp'], name='app_permiss_action_a03ba4_idx'), models.Index(fields=['resource_type', 'resource_id'], name='app_permiss_resourc_3f91e7_idx')],
            },
        ),
    ]
