# Generated by Django 4.2.16 on 2025-11-16 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_permissionauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appraisal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_self', 'Chờ nhân viên tự đánh giá'), ('pending_manager', 'Chờ quản lý đánh giá'), ('pending_hr', 'Chờ HR phê duyệt'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='pending_self', max_length=20)),
                ('self_assessment_date', models.DateTimeField(blank=True, null=True)),
                ('manager_review_date', models.DateTimeField(blank=True, null=True)),
                ('final_review_date', models.DateTimeField(blank=True, null=True)),
                ('self_overall_score', models.DecimalField(blank=True, decimal_places=2, help_text='Tổng điểm tự đánh giá', max_digits=5, null=True)),
                ('self_comments', models.TextField(blank=True, help_text='Nhận xét của nhân viên')),
                ('self_achievements', models.TextField(blank=True, help_text='Thành tích nổi bật')),
                ('self_challenges', models.TextField(blank=True, help_text='Khó khăn gặp phải')),
                ('self_development_plan', models.TextField(blank=True, help_text='Kế hoạch phát triển')),
                ('manager_overall_score', models.DecimalField(blank=True, decimal_places=2, help_text='Tổng điểm đánh giá của quản lý', max_digits=5, null=True)),
                ('manager_comments', models.TextField(blank=True, help_text='Nhận xét của quản lý')),
                ('manager_strengths', models.TextField(blank=True, help_text='Điểm mạnh')),
                ('manager_weaknesses', models.TextField(blank=True, help_text='Điểm cần cải thiện')),
                ('manager_recommendations', models.TextField(blank=True, help_text='Đề xuất (thăng chức, tăng lương, đào tạo...)')),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, help_text='Điểm cuối cùng (sau khi HR review)', max_digits=5, null=True)),
                ('overall_rating', models.CharField(blank=True, choices=[('outstanding', 'Xuất sắc'), ('exceeds', 'Vượt mong đợi'), ('meets', 'Đạt yêu cầu'), ('needs_improvement', 'Cần cải thiện'), ('unsatisfactory', 'Không đạt')], max_length=20, null=True)),
                ('hr_comments', models.TextField(blank=True, help_text='Nhận xét của HR')),
                ('salary_adjustment', models.DecimalField(blank=True, decimal_places=2, help_text='Điều chỉnh lương (nếu có)', max_digits=15, null=True)),
                ('promotion_recommended', models.BooleanField(default=False)),
                ('training_recommended', models.TextField(blank=True, help_text='Khóa đào tạo đề xuất')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='app.employee')),
                ('manager', models.ForeignKey(help_text='Người quản lý trực tiếp đánh giá', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_appraisals', to='app.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppraisalPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên kỳ đánh giá (VD: Đánh giá năm 2025)', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Mô tả mục đích, phạm vi đánh giá')),
                ('start_date', models.DateField(help_text='Ngày bắt đầu kỳ đánh giá')),
                ('end_date', models.DateField(help_text='Ngày kết thúc kỳ đánh giá')),
                ('self_assessment_deadline', models.DateField(help_text='Deadline nhân viên tự đánh giá')),
                ('manager_review_deadline', models.DateField(help_text='Deadline quản lý hoàn thành đánh giá')),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('active', 'Đang diễn ra'), ('closed', 'Đã kết thúc'), ('archived', 'Lưu trữ')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_departments', models.ManyToManyField(blank=True, help_text='Phòng ban áp dụng (để trống = tất cả)', to='app.department')),
                ('applicable_job_titles', models.ManyToManyField(blank=True, help_text='Chức danh áp dụng (để trống = tất cả)', to='app.jobtitle')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appraisal_periods', to='app.employee')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='AppraisalCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên tiêu chí (VD: Chất lượng công việc)', max_length=200)),
                ('description', models.TextField(help_text='Mô tả chi tiết tiêu chí')),
                ('category', models.CharField(choices=[('performance', 'Hiệu suất công việc'), ('behavior', 'Hành vi & Thái độ'), ('skill', 'Kỹ năng chuyên môn'), ('leadership', 'Năng lực lãnh đạo'), ('development', 'Phát triển bản thân')], max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, help_text='Trọng số (%) - tổng các tiêu chí = 100%', max_digits=5)),
                ('max_score', models.IntegerField(default=5, help_text='Điểm tối đa (thường là 5 hoặc 10)')),
                ('order', models.IntegerField(default=0, help_text='Thứ tự hiển thị')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='app.appraisalperiod')),
            ],
            options={
                'verbose_name': 'Appraisal Criterion',
                'verbose_name_plural': 'Appraisal Criteria',
                'ordering': ['period', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AppraisalComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_type', models.CharField(choices=[('employee', 'Nhân viên'), ('manager', 'Quản lý'), ('hr', 'HR')], max_length=20)),
                ('content', models.TextField(help_text='Nội dung góp ý')),
                ('is_private', models.BooleanField(default=False, help_text='Chỉ HR và quản lý thấy')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.appraisal')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='appraisal',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='app.appraisalperiod'),
        ),
        migrations.CreateModel(
            name='AppraisalScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_score', models.IntegerField(blank=True, help_text='Điểm tự đánh giá', null=True)),
                ('self_comment', models.TextField(blank=True, help_text='Giải thích điểm tự đánh giá')),
                ('manager_score', models.IntegerField(blank=True, help_text='Điểm quản lý đánh giá', null=True)),
                ('manager_comment', models.TextField(blank=True, help_text='Giải thích điểm quản lý')),
                ('final_score', models.IntegerField(blank=True, help_text='Điểm cuối cùng', null=True)),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='app.appraisal')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.appraisalcriteria')),
            ],
            options={
                'ordering': ['criteria__order', 'criteria__name'],
                'unique_together': {('appraisal', 'criteria')},
            },
        ),
        migrations.AddIndex(
            model_name='appraisalperiod',
            index=models.Index(fields=['status', '-start_date'], name='app_apprais_status_6170b0_idx'),
        ),
        migrations.AddIndex(
            model_name='appraisal',
            index=models.Index(fields=['period', 'status'], name='app_apprais_period__fbfd9e_idx'),
        ),
        migrations.AddIndex(
            model_name='appraisal',
            index=models.Index(fields=['employee', '-created_at'], name='app_apprais_employe_3e584f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='appraisal',
            unique_together={('period', 'employee')},
        ),
    ]
